version: '3.7'

services: 
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    expose: 
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/run/postgresql:/var/run/postgresql
  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/tag-api
    env_file:
      - .env.development
    depends_on:
      - db
  client:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/tag-client
    env_file:
      - .env.development
    depends_on:
      - db
