version: '3.7'

services: 
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    expose: 
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/run/postgresql:/var/run/postgresql
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.development
    depends_on:
      - db
    volumes:
      - ./api:/app
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - api
    volumes:
      - ./client:/app-client
  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin
  #   command: server /data
  #   volumes:
  #     - minio_data:/data

# volumes:
#   minio_data:
#
